### ISSUE TITLE
Attach file job is failing on demo

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hybox#202]
```
I, [2016-05-24T16:36:26.474207 #1833]  INFO -- : [ActiveJob] [AttachFilesToWorkJob] [854a6bfc-434e-478a-b8e0-561e450bbb0e] Performed AttachFilesToWorkJob from BetterActiveElasticJob(ingest) in 3569.98ms
F, [2016-05-24T16:36:26.476869 #1833] FATAL -- : 
Errno::ENOENT (No such file or directory @ rb_sysopen - uploads/sufia/uploaded_file/file/4/image.jp2):
  lib/active_job_tenant.rb:25:in `block in perform_now'
  lib/active_job_tenant.rb:43:in `block in switch'
  lib/active_job_tenant.rb:40:in `switch'
  lib/active_job_tenant.rb:24:in `perform_now'
```

**Comment by jcoyne** [comment]
I suspect a change is needed here: https://github.com/projecthydra/sufia/blob/8815463ed58fdf61921dcbe0ecdd0f41671107e6/app/jobs/attach_files_to_work_job.rb#L13
