### ISSUE TITLE
Workers can not find fits.sh on AWS

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hybox#208]
```
RuntimeError (Unable to execute command "fits.sh -i "/tmp/9c67wm83m20160525-7495-hqjhn320160525-7495-ji96mu""
sh: fits.sh: command not found
):
  lib/active_job_tenant.rb:25:in `block in perform_now'
  lib/active_job_tenant.rb:43:in `block in switch'
  lib/active_job_tenant.rb:40:in `switch'
  lib/active_job_tenant.rb:24:in `perform_now'
``

**Comment by mjgiarlo** [comment]
Fixed?
