### ISSUE TITLE
CSV ingest is not setting depositor correctly

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hybox#222]
```
$ ./bin/import_from_csv localhost spec/fixtures/csv/gse_metadata.csv
Files directory was left blank. No files will be ingested
Loading environment...
Starting import...
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-10.0.0.beta3/lib/active_fedora/validations.rb:89:in `raise_validation_error': Validation failed: Edit users Depositor must have edit access (ActiveFedora::RecordInvalid)
	from /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-10.0.0.beta3/lib/active_fedora/validations.rb:56:in `save!'
	from /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-10.0.0.beta3/lib/active_fedora/associations/builder/orders.rb:47:in `save!'
	from /Users/jcoyne/workspace/hybox/lib/importer/factory/object_factory.rb:44:in `block in update'
```

**Comment by jcoyne** [comment]
This was because I hadn't cleaned out my account correctly. I needed to call `Account.first.switch!` prior to running `ActiveFedora::Cleaner.clean!`
