### ISSUE TITLE
Java error on worker machine.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hybox#227]
```
[ec2-user@ip-10-0-1-161 ~]$ fits.sh -i /var/app/current/tmp/uploads/vt/15/0j/24/vt150j24620160528-23269-1nswg75
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/harvard/hul/ois/fits/Fits : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

```
$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (amzn-2.6.6.1.67.amzn1-x86_64 u101-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

I think we need JDK 1.8

**Comment by jcoyne** [comment]
I think this is only for the ec2-user and not the webapp user.
